baseurl = "http://kalafut.net"
languageCode = "en-us"
title = "Jim Kalafut"
pygmentsstyle = "friendly"

theme = "hyde-y"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  logo = "/favicon-310a.jpg"

# You can use markdown here.
  #brand = "Jim Kalafut"
  #topline = "Sherwood, Oregon"
  #footline = "code with <i class='fa fa-heart'></i>"

# Sidebar position
# false, true, "left", "right"
  sidebar = "left"

# Text for the top menu link, which goes the root URL for the site.
# Default (if omitted) is "Home".
  home = "Home"

# Select a syntax highight.
# Check the static/css/highlight directory for options.
  highlight = "default"

# Google Analytics.
  googleAnalytics = "Your Google Analytics tracking code"

# Sidebar social links.
  github = "kalafut" # Your Github profile ID
  bitbucket = "" # Your Bitbucket profile ID
  linkedin = "kalafut" # Your LinkedIn profile ID (from public URL)
  googleplus = "" # Your Google+ profile ID
  facebook = "" # Your Facebook profile ID
  twitter = "jimkalafut" # Your Twitter profile ID
  youtube = ""  # Your Youtube channel ID
  flattr = ""  # populate with your flattr uid

[blackfriday]
  angledQuotes = false
  fractions = false
  hrefTargetBlank = false
  latexDashes = true
  plainIdAnchors = true
  extensions = []
  extensionmask = []

