# Site settings
title: Broken Mold
email: jim@kalafut.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/brokenmold" # the subpath of your site, e.g. /blog/
url: "http://brokenmold.net" # the base hostname & protocol for your site
twitter_username: jimkalafut
github_username:  kalafut

# Build settings
markdown: kramdown
exclude: [draft/]
